services:
  frontend:
    build: ./frontend        # Look in the frontend folder for the Dockerfile
    container_name: student-frontend
    networks:
      - caddy_network
    ports:
      - "8080:3000"  # Map Laptop Port 8080 -> Container Port 3000
    labels:
      # Use the IP address as the site header
      caddy: 131.217.174.85
      
      # 1. Match only requests starting with /lfwells
      caddy.handle_path: /lfwells/*
      
      # 2. Inside that handle, proxy to the app (stripping the prefix)
      caddy.handle_path.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy_network:
    external: true